name: Create release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Bonita platform version'
        required: true 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Script to build all core components of the Bonita platform ${{ github.event.inputs.tag_name }}
          tag_name:  ${{ github.event.inputs.tag_name }}